-- Synthetic TPC-DS-style query log (99 statements) for canoniq's
-- file-mode query log connector. Statements are semicolon-separated,
-- one canonical query shape repeated with varying literals to
-- exercise parameterized grouping, plus a handful of unique
-- structural variants. Not the official TPC-DS 99 benchmark queries.

SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2001 GROUP BY d_year;
SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2002 GROUP BY d_year;
SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2003 GROUP BY d_year;
SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2001 GROUP BY d_year;
SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2002 GROUP BY d_year;
SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2003 GROUP BY d_year;
SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2001 GROUP BY d_year;
SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2002 GROUP BY d_year;
SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2003 GROUP BY d_year;
SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2001 GROUP BY d_year;
SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2002 GROUP BY d_year;
SELECT d_year, SUM(ss_net_profit) AS total_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk WHERE d_year = 2003 GROUP BY d_year;
SELECT COUNT(DISTINCT ss_customer_sk) AS distinct_customers FROM store_sales;
SELECT COUNT(DISTINCT ss_customer_sk) AS distinct_customers FROM store_sales;
SELECT COUNT(DISTINCT ss_customer_sk) AS distinct_customers FROM store_sales;
SELECT COUNT(DISTINCT ss_customer_sk) AS distinct_customers FROM store_sales;
SELECT COUNT(DISTINCT ss_customer_sk) AS distinct_customers FROM store_sales;
SELECT COUNT(DISTINCT ss_customer_sk) AS distinct_customers FROM store_sales;
SELECT COUNT(DISTINCT ss_customer_sk) AS distinct_customers FROM store_sales;
SELECT COUNT(DISTINCT ss_customer_sk) AS distinct_customers FROM store_sales;
SELECT SUM(ss_ext_sales_price) AS total_ext_sales FROM store_sales WHERE ss_store_sk = 1;
SELECT SUM(ss_ext_sales_price) AS total_ext_sales FROM store_sales WHERE ss_store_sk = 2;
SELECT SUM(ss_ext_sales_price) AS total_ext_sales FROM store_sales WHERE ss_store_sk = 1;
SELECT SUM(ss_ext_sales_price) AS total_ext_sales FROM store_sales WHERE ss_store_sk = 2;
SELECT SUM(ss_ext_sales_price) AS total_ext_sales FROM store_sales WHERE ss_store_sk = 1;
SELECT SUM(ss_ext_sales_price) AS total_ext_sales FROM store_sales WHERE ss_store_sk = 2;
SELECT SUM(ss_ext_sales_price) AS total_ext_sales FROM store_sales WHERE ss_store_sk = 1;
SELECT SUM(ss_ext_sales_price) AS total_ext_sales FROM store_sales WHERE ss_store_sk = 2;
SELECT AVG(ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk WHERE item.i_category = 'Books';
SELECT AVG(ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk WHERE item.i_category = 'Children';
SELECT AVG(ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk WHERE item.i_category = 'Music';
SELECT AVG(ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk WHERE item.i_category = 'Books';
SELECT AVG(ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk WHERE item.i_category = 'Children';
SELECT AVG(ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk WHERE item.i_category = 'Music';
SELECT AVG(ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk WHERE item.i_category = 'Books';
SELECT AVG(ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk WHERE item.i_category = 'Children';
SELECT AVG(ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk WHERE item.i_category = 'Music';
SELECT ss_store_sk, SUM(ss_quantity) AS total_qty FROM store_sales GROUP BY ss_store_sk;
SELECT ss_store_sk, SUM(ss_quantity) AS total_qty FROM store_sales GROUP BY ss_store_sk;
SELECT ss_store_sk, SUM(ss_quantity) AS total_qty FROM store_sales GROUP BY ss_store_sk;
SELECT ss_store_sk, SUM(ss_quantity) AS total_qty FROM store_sales GROUP BY ss_store_sk;
SELECT ss_store_sk, SUM(ss_quantity) AS total_qty FROM store_sales GROUP BY ss_store_sk;
SELECT ss_store_sk, SUM(ss_quantity) AS total_qty FROM store_sales GROUP BY ss_store_sk;
SELECT COUNT(*) AS high_profit_orders FROM store_sales WHERE ss_net_profit > 10;
SELECT COUNT(*) AS high_profit_orders FROM store_sales WHERE ss_net_profit > 20;
SELECT COUNT(*) AS high_profit_orders FROM store_sales WHERE ss_net_profit > 30;
SELECT COUNT(*) AS high_profit_orders FROM store_sales WHERE ss_net_profit > 10;
SELECT COUNT(*) AS high_profit_orders FROM store_sales WHERE ss_net_profit > 20;
SELECT COUNT(*) AS high_profit_orders FROM store_sales WHERE ss_net_profit > 30;
SELECT COUNT(*) AS high_profit_orders FROM store_sales WHERE ss_net_profit > 10;
SELECT SUM(cs_net_profit) AS total_catalog_profit FROM catalog_sales;
SELECT SUM(cs_net_profit) AS total_catalog_profit FROM catalog_sales;
SELECT SUM(cs_net_profit) AS total_catalog_profit FROM catalog_sales;
SELECT SUM(cs_net_profit) AS total_catalog_profit FROM catalog_sales;
SELECT SUM(cs_net_profit) AS total_catalog_profit FROM catalog_sales;
SELECT SUM(ws_net_profit) AS total_web_profit FROM web_sales;
SELECT SUM(ws_net_profit) AS total_web_profit FROM web_sales;
SELECT SUM(ws_net_profit) AS total_web_profit FROM web_sales;
SELECT SUM(ws_net_profit) AS total_web_profit FROM web_sales;
SELECT SUM(ws_net_profit) AS total_web_profit FROM web_sales;
SELECT COUNT(DISTINCT c_customer_sk) AS distinct_customers FROM customer;
SELECT COUNT(DISTINCT c_customer_sk) AS distinct_customers FROM customer;
SELECT COUNT(DISTINCT c_customer_sk) AS distinct_customers FROM customer;
SELECT COUNT(DISTINCT c_customer_sk) AS distinct_customers FROM customer;
SELECT SUM(sr_return_amt) AS total_returns FROM store_returns;
SELECT SUM(sr_return_amt) AS total_returns FROM store_returns;
SELECT SUM(sr_return_amt) AS total_returns FROM store_returns;
SELECT SUM(sr_return_amt) AS total_returns FROM store_returns;
SELECT SUM(sr_return_amt) AS total_returns FROM store_returns;
SELECT store.s_state, SUM(store_sales.ss_net_profit) AS state_profit FROM store_sales JOIN store ON store_sales.ss_store_sk = store.s_store_sk GROUP BY store.s_state;
SELECT store.s_state, SUM(store_sales.ss_net_profit) AS state_profit FROM store_sales JOIN store ON store_sales.ss_store_sk = store.s_store_sk GROUP BY store.s_state;
SELECT store.s_state, SUM(store_sales.ss_net_profit) AS state_profit FROM store_sales JOIN store ON store_sales.ss_store_sk = store.s_store_sk GROUP BY store.s_state;
SELECT store.s_state, SUM(store_sales.ss_net_profit) AS state_profit FROM store_sales JOIN store ON store_sales.ss_store_sk = store.s_store_sk GROUP BY store.s_state;
SELECT store.s_state, SUM(store_sales.ss_net_profit) AS state_profit FROM store_sales JOIN store ON store_sales.ss_store_sk = store.s_store_sk GROUP BY store.s_state;
SELECT store.s_state, SUM(store_sales.ss_net_profit) AS state_profit FROM store_sales JOIN store ON store_sales.ss_store_sk = store.s_store_sk GROUP BY store.s_state;
SELECT store.s_state, SUM(store_sales.ss_net_profit) AS state_profit FROM store_sales JOIN store ON store_sales.ss_store_sk = store.s_store_sk GROUP BY store.s_state;
SELECT item.i_brand, AVG(store_sales.ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk GROUP BY item.i_brand;
SELECT item.i_brand, AVG(store_sales.ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk GROUP BY item.i_brand;
SELECT item.i_brand, AVG(store_sales.ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk GROUP BY item.i_brand;
SELECT item.i_brand, AVG(store_sales.ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk GROUP BY item.i_brand;
SELECT item.i_brand, AVG(store_sales.ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk GROUP BY item.i_brand;
SELECT item.i_brand, AVG(store_sales.ss_sales_price) AS avg_price FROM store_sales JOIN item ON store_sales.ss_item_sk = item.i_item_sk GROUP BY item.i_brand;
SELECT date_dim.d_year, date_dim.d_moy, SUM(store_sales.ss_net_profit) AS monthly_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk GROUP BY date_dim.d_year, date_dim.d_moy;
SELECT date_dim.d_year, date_dim.d_moy, SUM(store_sales.ss_net_profit) AS monthly_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk GROUP BY date_dim.d_year, date_dim.d_moy;
SELECT date_dim.d_year, date_dim.d_moy, SUM(store_sales.ss_net_profit) AS monthly_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk GROUP BY date_dim.d_year, date_dim.d_moy;
SELECT date_dim.d_year, date_dim.d_moy, SUM(store_sales.ss_net_profit) AS monthly_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk GROUP BY date_dim.d_year, date_dim.d_moy;
SELECT date_dim.d_year, date_dim.d_moy, SUM(store_sales.ss_net_profit) AS monthly_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk GROUP BY date_dim.d_year, date_dim.d_moy;
SELECT date_dim.d_year, date_dim.d_moy, SUM(store_sales.ss_net_profit) AS monthly_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk GROUP BY date_dim.d_year, date_dim.d_moy;
SELECT date_dim.d_year, date_dim.d_moy, SUM(store_sales.ss_net_profit) AS monthly_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk GROUP BY date_dim.d_year, date_dim.d_moy;
SELECT date_dim.d_year, date_dim.d_moy, SUM(store_sales.ss_net_profit) AS monthly_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk GROUP BY date_dim.d_year, date_dim.d_moy;
SELECT date_dim.d_year, date_dim.d_moy, SUM(store_sales.ss_net_profit) AS monthly_profit FROM store_sales JOIN date_dim ON store_sales.ss_sold_date_sk = date_dim.d_date_sk GROUP BY date_dim.d_year, date_dim.d_moy;
SELECT COUNT(*) AS promo_count FROM promotion;
SELECT COUNT(*) AS promo_count FROM promotion;
SELECT COUNT(*) AS promo_count FROM promotion;
SELECT MAX(cs_list_price) AS max_price FROM catalog_sales;
SELECT MIN(ws_list_price) AS min_price FROM web_sales;
SELECT customer.c_first_name, customer.c_last_name FROM customer WHERE customer.c_preferred_cust_flag = 'Y';
SELECT AVG(cs_quantity) AS avg_catalog_qty FROM catalog_sales WHERE cs_item_sk = 1;
SELECT SUM(ws_quantity) AS total_web_qty FROM web_sales JOIN item ON web_sales.ws_item_sk = item.i_item_sk WHERE item.i_class = 'birdal';
